config/routes.rb
Rails.application.routes.draw do

  resources :wallpapers

  # get 'about', to: 'page#about'
  # get 'page/home'

  %w[about home].each do |page|
    get page, controller: "page", action: page
  end

  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'

    get 'sign_in', to: 'devise/sessions#new'
  end

  resources :videos
  resources :galleries
  resources :links

  resources :pins do
  	member do
  		put "like",    to: "pins#upvote"
  	end

    get 'murals', :on => :collection
    get 'illustrations', :on => :collection
    get 'publications', :on => :collection

  end

  root "page#home"
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	acts_as_votable
	belongs_to :category
	belongs_to :user
	belongs_to :gallery

	has_attached_file :image,
		:path => ":rails_root/public/images/:id/:filename",
		:url  => "/images/:id/:filename"

	has_attached_file :image, :styles => { :medium => "300x300>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	layout "app"
	
	before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:murals, :illustrations, :publications, :show]

	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def murals
		@pins = Pin.where("category_id = ?", 1).order("created_at DESC")
	end

	def illustrations
		@pins = Pin.where("category_id = ?", 2).order("created_at DESC")
	end

	def publications
		@pins = Pin.where("category_id = ?", 3).order("created_at DESC")
	end

	def show
	end

	def new
		@pin = current_user.pins.build
	end

	def create
		@pin = current_user.pins.build(pin_params)

		if @pin.save
			redirect_to @pin, notice: "Pin was successfully created"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Pin was successfully updated"
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end

	def upvote
		@pin.upvote_by current_user
		redirect_to :back
	end

	private

	def pin_params
		params.require(:pin).permit(:title, :description, :image, :category_id)
	end

	def find_pin
		@pin = Pin.find(params[:id])
	end

end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
	- if @pin.errors.any?
		#errors
			%h2
				= pluralize(@pin.errors.count, "error")
				prevented this Pin from saving
			%ul
				- @pin.errors.full_messages.each do |msg|
					%li= msg

	.form-group
		%p= f.label "Select a category for the image to be palced in :-"
		= f.collection_select :category_id, Category.order("id ASC"), :id, :name, {selected: 4}, { class: "form-control" }

	%br

	.form-group
		= f.input :image, input_html: { class: 'form-control' }

	%br

	.form-group
		= f.input :title, input_html: { class: 'form-control' }

	.form-group
		= f.input :description, input_html: { class: 'form-control' }

	.form-group.btn-group
		= f.submit "Upload Image", class: "btn btn-primary"
		= link_to "Back", :back, class: "btn btn-default"

app/views/pins/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit Your Image
			.panel-body
				.current_image
					%strong.center Current Image
					= image_tag @pin.image.url(:medium)
				= render 'form'

.related.social-list
	= link_to "https://www.facebook.com/eye.dealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-facebook
	= link_to "https://twitter.com/eyedealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-twitter
	= link_to "https://www.instagram.com/eye.dealist", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-instagram

app/views/pins/illustrations.html.haml
= provide(:title, "Eyedealist | Illustrations")

%header.codrops-header
	= image_tag "illustrations.png", :size => "200x124"

#pins.transitions-enabled
	
	- @pins.each do |pin|
		
		.box.panel.panel-default
			
			= link_to (image_tag pin.image), pin.image.url, "data-lightbox" => "illustrations", "data-title" => "#{pin.title}"
			
			- if user_signed_in?
				%p.user	
					.btn-group
						= link_to "Edit", edit_pin_path(pin), class: "btn btn-default"
						= link_to "Delete", pin_path(pin), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"

.related.social-list
	= link_to "https://www.facebook.com/eye.dealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-facebook
	= link_to "https://twitter.com/eyedealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-twitter
	= link_to "https://www.instagram.com/eye.dealist", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-instagram

app/views/pins/index.html.haml
= provide(:title, "Eyedealist | All Images")

%header.codrops-header
	= link_to murals_pins_path do
		= image_tag "murals.png", :size => "100x62"
	= link_to illustrations_pins_path do
		= image_tag "illustrations.png", :size => "100x62"
	= link_to publications_pins_path do
		= image_tag "publications.png", :size => "100x62"

#pins.transitions-enabled
	- @pins.each do |pin|
		.box.panel.panel-default
			= link_to (image_tag pin.image), pin_path(pin)
			%p.user
				- if user_signed_in?
					.btn-group
						= link_to "Edit", edit_pin_path(pin), class: "btn btn-default"
						= link_to "Delete", pin_path(pin), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"
.related.social-list
	= link_to "https://www.facebook.com/eye.dealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-facebook
	= link_to "https://twitter.com/eyedealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-twitter
	= link_to "https://www.instagram.com/eye.dealist", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-instagram

app/views/pins/murals.html.haml
= provide(:title, "Eyedealist | Murals")

%header.codrops-header
	= image_tag "murals.png", :size => "200x124"

#pins.transitions-enabled
	
	- @pins.each do |pin|
		
		.box.panel.panel-default
			
			= link_to (image_tag pin.image), pin.image.url, "data-lightbox" => "murals", "data-title" => "#{pin.title}"
			
			- if user_signed_in?
				%p.user
					.btn-group
						= link_to "Edit", edit_pin_path(pin), class: "btn btn-default"
						= link_to "Delete", pin_path(pin), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"

.related.social-list
	= link_to "https://www.facebook.com/eye.dealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-facebook
	= link_to "https://twitter.com/eyedealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-twitter
	= link_to "https://www.instagram.com/eye.dealist", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-instagram

app/views/pins/new.html.haml
= provide(:title, "Eyedealist | Upload Image")

.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Upload A New Image
			.panel-body
				= render 'form'

.related.social-list
	= link_to "https://www.facebook.com/eye.dealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-facebook
	= link_to "https://twitter.com/eyedealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-twitter
	= link_to "https://www.instagram.com/eye.dealist", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-instagram

app/views/pins/publications.html.haml
= provide(:title, "Eyedealist | Publications")

%header.codrops-header
	= image_tag "publications.png", :size => "200x124"

#pins.transitions-enabled
	- @pins.each do |pin|
		.box.panel.panel-default
			= link_to (image_tag pin.image), pin.image.url, "data-lightbox" => "publications", "data-title" => "#{pin.title}"
			%p.user
				- if user_signed_in?
					.btn-group
						= link_to "Edit", edit_pin_path(pin), class: "btn btn-default"
						= link_to "Delete", pin_path(pin), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"

.related.social-list
	= link_to "https://www.facebook.com/eye.dealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-facebook
	= link_to "https://twitter.com/eyedealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-twitter
	= link_to "https://www.instagram.com/eye.dealist", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-instagram

app/views/pins/show.html.haml
= provide(:title, "Eyedealist | Image View")

#pin_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.panel-heading.pin_image
				= image_tag @pin.image.url
			.panel-body
				%h1= @pin.title
				%p.description= @pin.description
			- if user_signed_in?
				.panel-footer
					.row
						.col-md-6
							.btn-group.pull-right	
								= link_to "Edit", edit_pin_path, class: "btn btn-default"
								= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"

.related.social-list
	= link_to "https://www.facebook.com/eye.dealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-facebook
	= link_to "https://twitter.com/eyedealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-twitter
	= link_to "https://www.instagram.com/eye.dealist", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-instagram