config/routes.rb
Rails.application.routes.draw do

  resources :wallpapers

  # get 'about', to: 'page#about'
  # get 'page/home'

  %w[about home].each do |page|
    get page, controller: "page", action: page
  end

  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'

    get 'sign_in', to: 'devise/sessions#new'
  end

  resources :videos
  resources :galleries
  resources :links

  resources :pins do
  	member do
  		put "like",    to: "pins#upvote"
  	end

    get 'murals', :on => :collection
    get 'illustrations', :on => :collection
    get 'publications', :on => :collection

  end

  root "page#home"
end

app/models/video.rb
class Video < ActiveRecord::Base



	has_attached_file :image, :styles => { :tube => "348x234>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	layout "app"

	before_action :find_video, only: [:show, :edit, :update, :destroy, :link]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@videos = Video.all.order("created_at DESC")
	end

	def show
		@video.link
	end

	def new
		@video = Video.new
	end

	def create
		@video = Video.new(video_params)

		@newvideo = @video
		@newvideo.link = @newvideo.link.split('=').last

		if @video.save

			redirect_to @video
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @video.update(pin_params)
			redirect_to @Video, notice: "Video was successfully updated"
		else
			render 'edit'
		end
	end

	def destroy
		@video.destroy
		redirect_to root_path
	end

	private

		def find_video
			@video = Video.find(params[:id])
		end

		def video_params
			params.require(:video).permit(:title, :link, :image)
		end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.haml
= simple_form_for @video, html: { multipart: true } do |f|
	- if @video.errors.any?
		#errors
			%h2
				= pluralize(@video.errors.count, "error")
				prevented this Pin from saving
			%ul
				- @video.errors.full_messages.each do |msg|
					%li= msg

	.form-group
		= f.input :title, input_html: { class: 'form-control' }

	.form-group
		= f.input :link, input_html: { class: 'form-control' }

	.form-group
		= f.label "Choose your image here:-"
		= f.file_field :image, as: :file, input_html: { class: 'form-control' }

	.form-group.btn-group
		= f.submit :submit, class: "btn btn-primary"
		= link_to "Back", :back, class: "btn btn-default"

app/views/videos/edit.html.haml
= provide(:title, "Eyedealist | Eit Video")

#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1= "Edit: "+@video.title
			.panel-body
				.current_image
					%strong.center Current Video
					%iframe{:allowscriptaccess => "always", :allowFullScreen => "true", :frameborder => "0", :src => "http://www.youtube.com/embed/"+@video.link, :title => "YouTube video player", :width => "640", :height => "430"}
				= render 'form'

app/views/videos/index.html.haml
= provide(:title, "Eyedealist | Videos")

%header.codrops-header
	= image_tag "videos.png", :size => "200x124"

#pins.transitions-enabled
	- @videos.each do |video|
		.box.panel.panel-default	
			%iframe{:allowscriptaccess => "always", :allowFullScreen => "true", :frameborder => "0", :src => "http://www.youtube.com/embed/"+video.link, :title => "YouTube video player", :width => "348", :height => "234"}
			- if user_signed_in?
				.btn-group
					= link_to "Edit", edit_video_path(video), class: "btn btn-default"
					= link_to "Delete", video_path(video), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"
					%br
					%br	
%br
%br

.related.social-list
	= link_to "https://www.facebook.com/eye.dealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-facebook
	= link_to "https://twitter.com/eyedealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-twitter
	= link_to "https://www.instagram.com/eye.dealist", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-instagram

app/views/videos/new.html.haml
= provide(:title, "Eyedealist | Upload Video")

.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Upload A New Video
			.panel-body
				= render 'form'

app/views/videos/show.html.haml
= provide(:title, "Eyedealist | Video")

#pin_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.panel-heading
				%iframe{:allowscriptaccess => "always", :allowFullScreen => "true", :frameborder => "0", :height => "430", :src => "http://www.youtube.com/embed/"+@video.link, :title => "YouTube video player", :width => "640"}
			.panel-body
				%h1= @video.title

			- if user_signed_in?
				.panel-footer
					.row
						.col-md-12
							.btn-group
								= link_to "Edit", edit_video_path, class: "btn btn-default"
								= link_to "Delete", video_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"