config/routes.rb
Rails.application.routes.draw do

  resources :wallpapers

  # get 'about', to: 'page#about'
  # get 'page/home'

  %w[about home].each do |page|
    get page, controller: "page", action: page
  end

  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'

    get 'sign_in', to: 'devise/sessions#new'
  end

  resources :videos
  resources :galleries
  resources :links

  resources :pins do
  	member do
  		put "like",    to: "pins#upvote"
  	end

    get 'murals', :on => :collection
    get 'illustrations', :on => :collection
    get 'publications', :on => :collection

  end

  root "page#home"
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	
	has_many :pins, :dependent => :destroy


end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  layout "app"

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery  = Gallery.find(params[:id])
    @pictures = @gallery.pins

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save

        if params[:images]
          # The magic is here ;)
          params[:images].each { |image|
            @gallery.pins.create(image: image)
          }
        end

        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(gallery_params)
        if params[:images]
          # The magic is here ;)
          params[:images].each { |image|
            @gallery.pins.create(image: image)
          }
        end
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end

  private

  def gallery_params
    params.require(:gallery).permit(:description,
                                    :name,
                                    :pins
                                   )
  end
end



  # def index
  # end

  # def new
  # end

  # def create
  # end

  # def edit
  # end

  # def update
  # end

  # def destroy
  # end

  # def show
  # end
# end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.haml
= simple_form_for @gallery, html: { multipart: true } do |f|
	- if @gallery.errors.any?
		#errors
			%h2
				= pluralize(@gallery.errors.count, "error")
				prevented this Gallery from saving
			%ul
				- @gallery.errors.full_messages.each do |msg|
					%li= msg

	.form-group
		= f.input :name, input_html: { class: 'form-control' }

	.form-group
		= f.input :description, input_html: { class: 'form-control' }

	.form-group
		= f.label "Select multiple images:-", :class => 'control-label'

		.control
			= file_field_tag "images[]", type: :file, multiple: true

	.form-group.btn-group
		= f.submit :submit, class: "btn btn-primary"
		= link_to "Back", :back, class: "btn btn-default"

app/views/galleries/edit.html.haml
= provide(:title, "Eyedealist | Edit Exhibition")

#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1= "Edit: "+@gallery.name
			.panel-body
				= render 'form'

.related.social-list
	= link_to "https://www.facebook.com/eye.dealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-facebook
	= link_to "https://twitter.com/eyedealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-twitter
	= link_to "https://www.instagram.com/eye.dealist", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-instagram

app/views/galleries/index.html.haml
= provide(:title, "Eyedealist | Exhibitions")

%header.codrops-header
	= image_tag "exhibitions.png", :size => "200x124"

#pins.transitions-enabled
	- @galleries.each do |gallery|

		- if gallery.pins.first

			.box.panel.panel-default
				= link_to (image_tag gallery.pins.first.image.url), gallery_path(gallery)
				= link_to gallery_path(gallery) do
					%h2= gallery.name.truncate(14)
		
				- if user_signed_in?
					%p.user
						.btn-group
							= link_to "Edit", edit_gallery_path(gallery), class: "btn btn-default"
							= link_to "Delete", gallery_path(gallery), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"

		- else

			.box.panel.panel-default
				N/A
				= link_to gallery_path(gallery) do
					%h2= gallery.name.truncate(14)
		
				- if user_signed_in?  
					%p.user
						.btn-group
							= link_to "Edit", edit_gallery_path(gallery), class: "btn btn-default"
							= link_to "Delete", gallery_path(gallery), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"

.related.social-list
	= link_to "https://www.facebook.com/eye.dealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-facebook
	= link_to "https://twitter.com/eyedealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-twitter
	= link_to "https://www.instagram.com/eye.dealist", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-instagram

app/views/galleries/new.html.haml
= provide(:title, "Eyedealist | Create Exhibition")

.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Create a New Gallery
			.panel-body
				= render 'form'
				
.related.social-list
	= link_to "https://www.facebook.com/eye.dealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-facebook
	= link_to "https://twitter.com/eyedealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-twitter
	= link_to "https://www.instagram.com/eye.dealist", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-instagram

app/views/galleries/show.html.haml
= provide(:title, "Eyedealist | Exhibition")

%header.codrops-header
	
	%h1= @gallery.name

	- if user_signed_in?
		
		= link_to 'Back', galleries_path, :class => 'btn btn-mini'
		
		= link_to 'Edit', edit_gallery_path(@gallery), :class => 'btn btn-mini'
		
		= link_to 'Delete gallery', gallery_path(@gallery), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-mini'

	.about-text.text-center
		%br
		
		= @gallery.description

		%br
		%hr
		%br

- unless @pictures.empty?
	
	#pins.transitions-enabled
		
		- @pictures.each do |pic|
			
			.box.panel.panel-default
				
				= link_to (image_tag pic.image), pic.image.url, "data-lightbox" => "#{@gallery.id}", "data-title" => "#{@gallery.name}"
				
				- if user_signed_in?
					
					= link_to "Delete Picture", pic, :data => { :confirm => "Are you sure?" }, :method => :delete

.related.social-list
	= link_to "https://www.facebook.com/eye.dealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-facebook
	= link_to "https://twitter.com/eyedealer", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-twitter
	= link_to "https://www.instagram.com/eye.dealist", target: '_blank' do
		%span.menu-icon.fa.fa-fw.fa-instagram