config/routes.rb
Rails.application.routes.draw do

  resources :wallpapers

  # get 'about', to: 'page#about'
  # get 'page/home'

  %w[about home].each do |page|
    get page, controller: "page", action: page
  end

  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'

    get 'sign_in', to: 'devise/sessions#new'
  end

  resources :videos
  resources :galleries
  resources :links

  resources :pins do
  	member do
  		put "like",    to: "pins#upvote"
  	end

    get 'murals', :on => :collection
    get 'illustrations', :on => :collection
    get 'publications', :on => :collection

  end

  root "page#home"
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :pins
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	
	has_many :pins, :dependent => :destroy


end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	acts_as_votable
	belongs_to :category
	belongs_to :user
	belongs_to :gallery

	has_attached_file :image,
		:path => ":rails_root/public/images/:id/:filename",
		:url  => "/images/:id/:filename"

	has_attached_file :image, :styles => { :medium => "300x300>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/models/video.rb
class Video < ActiveRecord::Base



	has_attached_file :image, :styles => { :tube => "348x234>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/wallpaper.rb
class Wallpaper < ActiveRecord::Base
	has_attached_file :image,
		:path => ":rails_root/public/images/:id/:filename",
		:url  => "/images/:id/:filename"
	
	has_attached_file :image, styles: { full: "1920x1080>", thumb: "100x56>", :medium => "300x300>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  layout "app"

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery  = Gallery.find(params[:id])
    @pictures = @gallery.pins

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save

        if params[:images]
          # The magic is here ;)
          params[:images].each { |image|
            @gallery.pins.create(image: image)
          }
        end

        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(gallery_params)
        if params[:images]
          # The magic is here ;)
          params[:images].each { |image|
            @gallery.pins.create(image: image)
          }
        end
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end

  private

  def gallery_params
    params.require(:gallery).permit(:description,
                                    :name,
                                    :pins
                                   )
  end
end



  # def index
  # end

  # def new
  # end

  # def create
  # end

  # def edit
  # end

  # def update
  # end

  # def destroy
  # end

  # def show
  # end
# end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  layout "app"

  before_action :find_link, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @links = Link.all.order("created_at DESC")
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)

    if @link.save
      redirect_to @link
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @link.update(link_params)
      redirect_to @link, notice: "Press link was successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
  end

  private

    def link_params
    
      params.require(:link).permit(:title, :url, :date)

    end

    def find_link
      @link = Link.find(params[:id])
    end












end

app/controllers/page_controller.rb
class PageController < ApplicationController
	layout "app"

	def about
	end

	def home
	end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	layout "app"
	
	before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:murals, :illustrations, :publications, :show]

	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def murals
		@pins = Pin.where("category_id = ?", 1).order("created_at DESC")
	end

	def illustrations
		@pins = Pin.where("category_id = ?", 2).order("created_at DESC")
	end

	def publications
		@pins = Pin.where("category_id = ?", 3).order("created_at DESC")
	end

	def show
	end

	def new
		@pin = current_user.pins.build
	end

	def create
		@pin = current_user.pins.build(pin_params)

		if @pin.save
			redirect_to @pin, notice: "Pin was successfully created"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Pin was successfully updated"
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end

	def upvote
		@pin.upvote_by current_user
		redirect_to :back
	end

	private

	def pin_params
		params.require(:pin).permit(:title, :description, :image, :category_id)
	end

	def find_pin
		@pin = Pin.find(params[:id])
	end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	layout "app"

	before_action :find_video, only: [:show, :edit, :update, :destroy, :link]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@videos = Video.all.order("created_at DESC")
	end

	def show
		@video.link
	end

	def new
		@video = Video.new
	end

	def create
		@video = Video.new(video_params)

		@newvideo = @video
		@newvideo.link = @newvideo.link.split('=').last

		if @video.save

			redirect_to @video
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @video.update(pin_params)
			redirect_to @Video, notice: "Video was successfully updated"
		else
			render 'edit'
		end
	end

	def destroy
		@video.destroy
		redirect_to root_path
	end

	private

		def find_video
			@video = Video.find(params[:id])
		end

		def video_params
			params.require(:video).permit(:title, :link, :image)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/wallpapers_helper.rb
module WallpapersHelper
end

app/views/layouts/app.html.haml
!!! 5
%html{lang: "en"}
%head
	%title= yield(:title)

	%meta{ "http-equiv" => "Content-Type", :content => "text/html; charset=utf-8" }
	%meta{ :content => "Eyedealist", :name => "author" }
	%meta{ :content => "Eyedealist is a Jamaica-based illustrator and mural painter at the vanguard of his generation.", :name => "description" }
	%meta{ :content => "jamaican, illustrator, muralist, eyedealist, painter", :name => "keywords" }
	%meta{ :content => "width=device-width, initial-scale=1.0", :name => "viewport" }
	%meta{ :content => "#FFD700", :name => "theme-color" }

	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
	

%body
	#perspective.perspective.effect-airbnb
		- if (current_page?(root_url)) && ( @wallpaper )
			.container{:style => "background-image: url(#{request.base_url}#{@wallpaper.image.url}"}
				%p
					%btn.btn.super-button#super-open#showMenu
						%br
						Menu

				.wrapper
					- flash.each do |name, msg|
						= content_tag :div, msg, class: "alert alert-info"
					= yield

			%nav.outer-nav.left.vertical
				= link_to root_path do
					%span.menu-icon.fa.fa-fw.fa-home
						%span.navi-text Home
				= link_to about_path do
					%span.menu-icon.fa.fa-fw.fa-address-book-o
						%span.navi-text About Me
				= link_to murals_pins_path do
					%span.menu-icon.fa.fa-fw.fa-google-wallet
						%span.navi-text Murals
				= link_to illustrations_pins_path do
					%span.menu-icon.fa.fa-fw.fa-pencil
						%span.navi-text Illustrations
				= link_to publications_pins_path do
					%span.menu-icon.fa.fa-fw.fa-leanpub
						%span.navi-text Publications
				= link_to galleries_path do
					%span.menu-icon.fa.fa-fw.fa-th
						%span.navi-text Exhibitons
				= link_to videos_path do
					%span.menu-icon.fa.fa-fw.fa-video-camera
						%span.navi-text Videos
				= link_to links_path do
					%span.menu-icon.fa.fa-fw.fa-newspaper-o
						%span.navi-text Press
				= link_to "https://twitter.com/eyedealer", target: '_blank' do
					%span.menu-icon.fa.fa-fw.fa-paint-brush
						%span.navi-text Paint Shop
				= link_to "https://twitter.com/eyedealer", target: '_blank' do
					%span.menu-icon.fa.fa-fw.fa-shopping-basket
						%span.navi-text Threads


			- if user_signed_in?
				.menu-wrap
					%nav.menu

						= link_to edit_user_registration_path, target: '_blank' do
							.profile
								= image_tag "the_eyedealist_profile.jpg", :size => '37x37'
								%span Matthew McCarthy

						.link-list
							= link_to new_pin_path do
								%span.menu-icon.fa.fa-fw.fa-image
								New Image
							= link_to pins_path do
								%span.menu-icon.fa.fa-fw.fa-image
								All Images
							= link_to new_video_path do
								%span.menu-icon.fa.fa-fw.fa-video-camera
								New Video
							= link_to new_gallery_path do
								%span.menu-icon.fa.fa-fw.fa-th-large
								New Gallery
							= link_to new_link_path do
								%span.menu-icon.fa.fa-fw.fa-newspaper-o
								New Press Link
							= link_to new_wallpaper_path do
								%span.menu-icon.fa.fa-fw.fa-image
								New Wallpaper
							= link_to wallpapers_path do
								%span.menu-icon.fa.fa-fw.fa-image
								All Wallpapers
							
						.icon-list
							= link_to "https://www.facebook.com/eye.dealer" do
								%span.menu-icon.fa.fa-fw.fa-facebook
							= link_to "https://twitter.com/eyedealer" do
								%span.menu-icon.fa.fa-fw.fa-twitter
							= link_to "https://www.instagram.com/eye.dealist" do
								%span.menu-icon.fa.fa-fw.fa-instagram
							= link_to destroy_user_session_path, :method => :delete do
								%span.menu-icon.fa.fa-fw.fa-power-off

				%btn.btn.menu-button#open-button
					%i.fa.fa-fw.fa-cogs
						%span Open Menu

		- else

			.container
				
				%p
					%btn.btn.super-button#super-open#showMenu
						%br
						Menu

				.wrapper
					- flash.each do |name, msg|
						= content_tag :div, msg, class: "alert alert-info"
					= yield

			%nav.outer-nav.left.vertical
				= link_to root_path do
					%span.menu-icon.fa.fa-fw.fa-home
						%span.navi-text Home
				= link_to about_path do
					%span.menu-icon.fa.fa-fw.fa-address-book-o
						%span.navi-text About Me
				= link_to murals_pins_path do
					%span.menu-icon.fa.fa-fw.fa-google-wallet
						%span.navi-text Murals
				= link_to illustrations_pins_path do
					%span.menu-icon.fa.fa-fw.fa-pencil
						%span.navi-text Illustrations
				= link_to publications_pins_path do
					%span.menu-icon.fa.fa-fw.fa-leanpub
						%span.navi-text Publications
				= link_to galleries_path do
					%span.menu-icon.fa.fa-fw.fa-th
						%span.navi-text Exhibitons
				= link_to videos_path do
					%span.menu-icon.fa.fa-fw.fa-video-camera
						%span.navi-text Videos
				= link_to links_path do
					%span.menu-icon.fa.fa-fw.fa-newspaper-o
						%span.navi-text Press
				= link_to "https://twitter.com/eyedealer", target: '_blank' do
					%span.menu-icon.fa.fa-fw.fa-paint-brush
						%span.navi-text Paint Shop
				= link_to "https://twitter.com/eyedealer", target: '_blank' do
					%span.menu-icon.fa.fa-fw.fa-shopping-basket
						%span.navi-text Threads

			- if user_signed_in?
				.menu-wrap
					%nav.menu

						= link_to edit_user_registration_path, target: '_blank' do
							.profile
								= image_tag "the_eyedealist_profile.jpg", :size => '37x37'
								%span Matthew McCarthy

						.link-list
							= link_to new_pin_path do
								%span.menu-icon.fa.fa-fw.fa-image
								New Image
							= link_to pins_path do
								%span.menu-icon.fa.fa-fw.fa-image
								All Images
							= link_to new_video_path do
								%span.menu-icon.fa.fa-fw.fa-video-camera
								New Video
							= link_to new_gallery_path do
								%span.menu-icon.fa.fa-fw.fa-th-large
								New Gallery
							= link_to new_link_path do
								%span.menu-icon.fa.fa-fw.fa-newspaper-o
								New Press Link
							= link_to new_wallpaper_path do
								%span.menu-icon.fa.fa-fw.fa-image
								New Wallpaper
							= link_to wallpapers_path do
								%span.menu-icon.fa.fa-fw.fa-image
								All Wallpapers

						.icon-list
							= link_to "https://www.facebook.com/eye.dealer", target: '_blank' do
								%span.menu-icon.fa.fa-fw.fa-facebook
							= link_to "https://twitter.com/eyedealer", target: '_blank' do
								%span.menu-icon.fa.fa-fw.fa-twitter
							= link_to "https://www.instagram.com/eye.dealist", target: '_blank' do
								%span.menu-icon.fa.fa-fw.fa-instagram
							= link_to destroy_user_session_path, :method => :delete do
								%span.menu-icon.fa.fa-fw.fa-power-off

				%btn.btn.menu-button#open-button
					%i.fa.fa-fw.fa-cogs
						%span Open Menu			


%script(src="/assets/modernizr.custom.25376.js")
%script(src="/assets/menu.js")
%script(src="/assets/classie.js")
%script(src="/assets/cogwheel.js")

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Eyedealist | Home
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
	

%body
	#perspective.perspective.effect-airbnb
		.container
			.wrapper
				
				- flash.each do |name, msg|
					= content_tag :div, msg, class: "alert alert-info"
				= yield


		%nav.outer-nav.left.vertical
			%ul.nav.navbar-nav.navbar-right
				%li= link_to "About", about_path
				%li= link_to "Photos", pins_path
				%li= link_to "Videos", videos_path
				%li= link_to "Press", links_path
				%li= link_to "New Press", new_link_path
				%li= link_to "New Image", new_pin_path
				%li= link_to "New Video", new_video_path
				%li= link_to "Account", edit_user_registration_path
				%li= link_to "Sign In", new_user_session_path
				
				- if user_signed_in?
					%ul.nav.navbar-nav.navbar-right
						%li= link_to "Sign Out", destroy_user_session_path, method: :delete

%script(src="/assets/modernizr.custom.25376.js")
%script(src="/assets/menu.js")
%script(src="/assets/classie.js")

app/views/page/about.html.haml
= provide(:title, "Eyedealist | About Me")

%header.codrops-header
	= image_tag "about.png", :size => "300x187"

.main.clearfix
	.container
		.col-md-4.section-title.text-center.left
			.col-md-4.text-center.img-responsive.left
			= image_tag "the_eyedealist.jpg"
		 
		.col-md-8.text-center.right
			.about-text
				%br
				%br
				%p
					Matthew McCarthy is a Jamaica-based illustrator and mural painter who has spent the last five years finding a way to combine his obsession with Jamaican street signs, old school dancehall illustrations and global street art movements. His style and overall message have been influenced by local and global happenings, which fuel his enormous need to formulate satire around interesting topics.
	
	.related.social-list
		= link_to "https://www.facebook.com/eye.dealer", target: '_blank' do
			%span.menu-icon.fa.fa-fw.fa-facebook
		= link_to "https://twitter.com/eyedealer", target: '_blank' do
			%span.menu-icon.fa.fa-fw.fa-twitter
		= link_to "https://www.instagram.com/eye.dealist", target: '_blank' do
			%span.menu-icon.fa.fa-fw.fa-instagram

app/views/page/home.html.haml
= provide(:title, "Eyedealist | Home")

.col-xs-2.col-xs-offset-5

	= link_to (image_tag "about.png", :height => '75', :class => "center-block"), about_path

	= link_to (image_tag "murals.png", :height => '75', :class => "center-block"), murals_pins_path


	= link_to (image_tag "illustrations.png", :height => '75', :class => "center-block"), illustrations_pins_path


	= link_to (image_tag "publications.png", :height => '75', :class => "center-block"), publications_pins_path


	= link_to (image_tag "exhibitions.png", :height => '75', :class => "center-block"), galleries_path


	= link_to (image_tag "videos.png", :height => '75', :class => "center-block"), videos_path


	= link_to (image_tag "press.png", :height => '75', :class => "center-block"), links_path


	= link_to (image_tag "paint_shop.png", :height => '75', :class => "center-block"), "https://twitter.com/eyedealer", target: '_blank'
	

	= link_to (image_tag "threads.png", :height => '75', :class => "center-block"), "https://twitter.com/eyedealer", target: '_blank'